# Site settings
title: Haos Dot Info
description: 'Benjamin Haos Information'
url: 'https://entropyhaos.github.io/haos_dot_info_site/'
baseurl: '/haos_dot_info_site/'
google_analytics: 'UA-92171668-1'
disqus_shortname: 'haos-info'

#baseurl: ""
port: 8080
host: 0.0.0.0

author:
  name: 'Benjamin Haos'
  email: benjaminhaos@gmail.com
  twitter_username: EntropyHaos
  #facebook_username: 
  github_username: EntropyHaos
  linkedin_username:  BenjaminHaos

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
